# Generated by Django 4.1.2 on 2022-10-12 12:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('schooling', models.CharField(choices=[('EB', 'Ensino Básico'), ('EF', 'Ensino Fundamental'), ('EM', 'Ensino Médio'), ('ES', 'Ensino Superior')], max_length=255, verbose_name='Escolaridade')),
                ('handed_skill', models.CharField(blank=True, choices=[('Canhoto', 'Canhoto'), ('Destro', 'Destro'), ('Ambidestro', 'Ambidestro')], max_length=255, null=True, verbose_name='Habilidade Manual')),
                ('sended_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='Enviado por')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
