# Generated by Django 4.1.2 on 2022-10-12 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_doctor_alter_patient_sended_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'Doutor', 'verbose_name_plural': 'Doutores'},
        ),
    ]
