# Generated by Django 4.1.2 on 2022-10-12 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reason',
            options={'verbose_name': 'Motivo de Encaminhamento', 'verbose_name_plural': 'Motivos de Encaminhamentos'},
        ),
    ]
